#!/usr/bin/env zsh

alias personal='mkcd ~/personal/'
alias config='pushd ~/.config/ >/dev/null && $EDITOR . && popd > /dev/null'
alias asdf='$(yabai --start-service &; skhd --start-service &;)'
alias fdsa='$(yabai --stop-service &; skhd --stop-service &;)'
alias rcedit='$EDITOR ~/.zshrc'
alias so='source ~/.zshrc'
alias vim='nvim'
alias idea='open -a "IntelliJ IDEA CE.app"'
alias rm='trash'
