#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
# yabai -m config focus_follows_mouse          off
# yabai -m config mouse_follows_focus          off
# yabai -m config window_origin_display        default
# yabai -m config window_placement             second_child
# yabai -m config window_topmost               off
# yabai -m config window_shadow                on
# yabai -m config window_opacity               off
# yabai -m config window_opacity_duration      0.0
# yabai -m config active_window_opacity        1.0
# yabai -m config normal_window_opacity        0.90
# yabai -m config window_border                off
# yabai -m config window_border_width          6
# yabai -m config active_window_border_color   0xff775759
# yabai -m config normal_window_border_color   0xff555555
# yabai -m config insert_feedback_color        0xffd75f5f
# yabai -m config split_ratio                  0.50
# yabai -m config auto_balance                 off
# yabai -m config mouse_modifier               fn
# yabai -m config mouse_action1                move
# yabai -m config mouse_action2                resize
# yabai -m config mouse_drop_action            swap

yabai -m config                              \
     external_bar                off:39:0     \
     mouse_follows_focus         on           \
     focus_follows_mouse         autoraise    \
     window_placement            second_child \
     window_topmost              off          \
     window_shadow               off          \
     window_opacity_duration     0.25         \
     active_window_opacity       0.90         \
     normal_window_opacity       0.50         \
     window_opacity              on           \
     insert_feedback_color       0xaad75f5f   \
     active_window_border_color  0xBF775759   \
     normal_window_border_color  0x7f353535   \
     window_border_width         2            \
     window_border_radius        12           \
     window_border_blur          on           \
     window_border_hidpi         on           \
     window_border               on           \
     split_ratio                 0.50         \
     split_type                  auto         \
     auto_balance                off          \
     top_padding                 10           \
     left_padding                10           \
     right_padding               10           \
     bottom_padding              10           \
     window_gap                  10           \
     layout                      bsp          \
     mouse_modifier              fn           \
     mouse_action1               move         \
     mouse_action2               resize       \
     mouse_drop_action           swap

# yabai -m config external_bar               all:39:0     \
#                 window_border              on           \
#                 mouse_follows_focus        off          \
#                 focus_follows_mouse        off          \
#                 window_placement           second_child \
#                 window_topmost             off          \
#                 window_shadow              float        \
#                 window_opacity             on           \
#                 window_opacity_duration    0.15         \
#                 active_window_opacity      1.0          \
#                 normal_window_opacity      0.95         \
#                 window_border_width        2            \
#                 window_border_radius       11           \
#                 window_animation_duration  0.15         \
#                 active_window_border_color 0xffe1e3e4   \
#                 normal_window_border_color 0xff2a2f38   \
#                 insert_feedback_color      0xff9dd274   \
#                 split_ratio                0.50         \
#                 auto_balance               off          \
#                 mouse_modifier             fn           \
#                 mouse_action1              move         \
#                 mouse_action2              resize       \
#                 mouse_drop_action          swap         \
#                 top_padding                20           \
#                 bottom_padding             10           \
#                 left_padding               10           \
#                 right_padding              10           \
#                 window_gap                 8

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  15
yabai -m config bottom_padding               15
yabai -m config left_padding                 15
# NOTE: for OBS floating head
# yabai -m config left_padding                 450
yabai -m config right_padding                15
yabai -m config window_gap                   15

# apps to not manage (ignore)
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Stickies" manage=off
yabai -m rule --add app="^Archive Utility$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off
yabai -m rule --add app="^Alfred Preferences$" manage=off
yabai -m rule --add app="^Music$" manage=off

# animations

echo "yabai configuration loaded.."
